export const systemQueries = [
  `"java.lang<type=OperatingSystem><>AvailableProcessors", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.nio<name=direct, type=BufferPool><>Count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>OpenFileDescriptorCount", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>SystemCpuLoad", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>CpuLoad", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>SystemLoadAverage", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>ProcessCpuLoad", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>FreeMemorySize", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>FreePhysicalMemorySize", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=OperatingSystem><>FreeSwapSpaceSize", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=ReplicaManager, name=LeaderCount><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
];

export const brokerQueries = [
  `"kafka.controller<type=KafkaController, name=ActiveBrokerCount><>Value", application="kafka", instance="broker1:5557", job="kafka"`,
  `"kafka.controller<type=KafkaController, name=GlobalPartitionCount><>Value", application="kafka", instance="broker1:5557", job="kafka"`,
  `"kafka.controller<type=KafkaController, name=GlobalTopicCount><>Value", application="kafka", instance="broker1:5557", job="kafka"`,
  `"kafka.controller<type=KafkaController, name=NewActiveControllersCount><>Value", application="kafka", instance="broker1:5557", job="kafka"`,
  `"kafka.controller<type=KafkaController, name=OfflinePartitionsCount><>Value", application="kafka", instance="broker1:5557", job="kafka"`,
  `"kafka.controller<type=KafkaController, name=LastAppliedRecordLagMs><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=BrokerMetadataListener, name=MetadataBatchSizes><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=BrokerMetadataListener, name=MetadataBatchProcessingTimeUs><>99thPercentile", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=MetadataLoader, name=CurrentControllerId><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=MetadataLoader, name=CurrentMetadataVersion><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=KafkaServer, name=BrokerState><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=txn-marker-channel-metrics><>request-size-avg", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>Count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=directory-assignments-metrics, BrokerId=3><>request-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=directory-assignments-metrics, BrokerId=3><>response-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=directory-assignments-metrics, BrokerId=3><>connection-creation-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=heartbeat-metrics, BrokerId=3><>connection-close-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=heartbeat-metrics, BrokerId=3><>connection-count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<name=G1 Eden Space, type=MemoryPool><PeakUsage>committed", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><Usage>used", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.controller<type=ControllerEventManager, name=EventQueueProcessingTimeMs><>StdDev", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.log<type=LogFlushStats, name=LogFlushRateAndTimeMs><>FifteenMinuteRate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=Processor, name=IdlePercent, networkProcessor=0><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=ErrorsPerSec, request=ApiVersions, error=NONE><>Count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=ControllerRegistration><>Min", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=ControllerRegistration><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=Vote><>Min", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=Vote><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=BeginQuorumEpoch><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestBytes, request=BeginQuorumEpoch><>Count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RemoteTimeMs, request=BeginQuorumEpoch><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RemoteTimeMs, request=ControllerRegistration><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RemoteTimeMs, request=Vote><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RemoteTimeMs, request=Vote><>Count", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=LocalTimeMs, request=ApiVersions><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=LocalTimeMs, request=ControllerRegistration><>StdDev", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.network<type=RequestMetrics, name=RequestQueueTimeMs, request=ApiVersions><>Max", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>incoming-byte-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>io-ratio", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>io-wait-ratio", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>outgoing-byte-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>select-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>request-size-avg", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=AddPartitionsManager-channel-metrics><>connection-close-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=alter-partition-metrics, BrokerId=3><>request-size-avg", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=ReplicaManager, name=PartitionCount><>Value", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=alter-partition-metrics, BrokerId=3><>connection-close-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=registration-metrics, BrokerId=3><>connection-creation-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=socket-server-metrics, listener=CONTROLLER, networkProcessor=0><>incoming-byte-total", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=socket-server-metrics, listener=CONTROLLER, networkProcessor=0><>io-ratio", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=socket-server-metrics, listener=CONTROLLER, networkProcessor=0><>io-wait-ratio", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=socket-server-metrics, listener=CONTROLLER, networkProcessor=0><>select-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=txn-marker-channel-metrics><>incoming-byte-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=txn-marker-channel-metrics><>io-ratio", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=txn-marker-channel-metrics><>network-io-rate", application="kafka", instance="broker3:5559", job="kafka"`,
  `"kafka.server<type=txn-marker-channel-metrics><>select-rate", application="kafka", instance="broker3:5559", job="kafka"`,
];

export const threadingQueries = [
  `"java.lang<type=Threading><>DaemonThreadCount", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=Threading><>PeakThreadCount", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=Threading><>SynchronizerUsageSupported", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=Threading><>TotalStartedThreadCount", application="kafka", instance="broker3:5559", job="kafka"`,
  `"java.lang<type=Threading><>TotalThreadAllocatedBytes", application="kafka", instance="broker1:5557", job="kafka"`,
  `"java.lang<type=Threading><>ThreadCpuTimeSupported", application="kafka", instance="broker3:5559", job="kafka"`,
];
